
# Note: This crate must be built using build.sh

[package]
name = "morgan-bpf-rust-iter"
version = "0.15.3"
description = "Morgan BPF iter program written in Rust"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
license = "Apache-2.0"
homepage = "https://morgan.com/"
edition = "2018"

[dependencies]
morgan-interface-bpf-utils = { path = "../../../../interface/bpf/rust-utils", version = "0.15.3"    }
[workspace]
members = []

[lib]
name = "morgan_bpf_rust_iter"
crate-type = ["cdylib"]
