[package]
name = "morgan-stake-api"
version = "0.15.3"
description = "Morgan Stake program API"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
license = "Apache-2.0"
homepage = "https://morgan.com/"
edition = "2018"

[dependencies]
bincode = "1.1.4"
log = "0.4.2"
serde = "1.0.91"
serde_derive = "1.0.91"
morgan-logger = { path = "../../logger", version = "0.15.3"     }
morgan-metricbot = { path = "../../metricbot", version = "0.15.3"     }
morgan-interface = { path = "../../interface", version = "0.15.3"     }
morgan-vote-api = { path = "../vote_api", version = "0.15.3"     }

[lib]
name = "morgan_stake_api"
crate-type = ["lib"]
