
[package]
name = "morgan-interface-bpf-utils"
version = "0.15.3"
description = "Morgan BPF SDK Rust Utils"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
license = "Apache-2.0"
homepage = "https://morgan.com/"
edition = "2018"

[workspace]
members = []
