[package]
name = "morgan-bpf-programs"
description = "Blockchain, Rebuilt for Scale"
version = "0.15.3"
documentation = "https://docs.rs/morgan"
homepage = "https://morgan.com/"
readme = "README.md"
repository = "https://github.com/morgan-labs/morgan"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
license = "Apache-2.0"
edition = "2018"

[features]
bpf_c = []
bpf_rust = []

[build-dependencies]
walkdir = "2"

[dependencies]
bincode = "1.1.4"
byteorder = "1.3.1"
elf = "0.0.10"
solana_rbpf = "=0.1.12"
morgan-bpfloader = { path = "../bpf_loader", version = "0.15.3"     }
morgan-logger = { path = "../../logger", version = "0.15.3"     }
morgan-runtime = { path = "../../runtime", version = "0.15.3"     }
morgan-interface = { path = "../../interface", version = "0.15.3"     }
[[bench]]
name = "bpf_loader"
