[package]
name = "morgan-failure-controller"
version = "0.15.3"
description = "Morgan failure controller"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
license = "Apache-2.0"
homepage = "https://morgan.com/"
edition = "2018"

[dependencies]
morgan-interface = { path = "../../interface", version = "0.15.3"     }
log = "0.4.2"

[dev-dependencies]
morgan-runtime = { path = "../../runtime", version = "0.15.3"     }

[lib]
name = "morgan_failure_controller"
crate-type = ["cdylib"]

