[package]
name = "morgan-noop-controller"
version = "0.15.3"
description = "Morgan noop controller"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
license = "Apache-2.0"
homepage = "https://morgan.com/"
edition = "2018"

[dependencies]
morgan-interface = { path = "../../interface", version = "0.15.3"     }
morgan-logger = { path = "../../logger", version = "0.15.3"     }
log = "0.4.2"

[lib]
name = "morgan_noop_controller"
crate-type = ["cdylib"]

