[package]
name = "morgan-interface"
version = "0.15.3"
description = "Morgan Interface"
authors = ["Morgan Maintainers <maintainers@morgan.com>"]
repository = "https://github.com/morgan-labs/morgan"
homepage = "https://morgan.com/"
license = "Apache-2.0"
edition = "2018"

[dependencies]
assert_matches = "1.3.0"
bincode = "1.1.4"
bs58 = "0.2.0"
hex = "0.3.2"
byteorder = "1.2.1"
chrono = { version = "0.4.0", features = ["serde"] }
generic-array = { version = "0.13.0", default-features = false, features = ["serde"] }
itertools = "0.8.0"
log = "0.4.2"
num-derive = "0.2"
num-traits = "0.2"
rand = "0.6.5"
rayon = "1.0.0"
sha2 = "0.8.0"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
solana-ed25519-dalek = "0.2.0"
untrusted = "0.6.2"
morgan-helper = { path = "../helper", version = "0.1.0"     }
