

[dependencies.compiler_builtins]
path = "../../../../interface/bpf/rust-bpf-sysroot/src/compiler-builtins"

[target.bpfel-unknown-unknown.dependencies]
alloc = { path = "../../../../interface/bpf/rust-bpf-sysroot/src/liballoc" }